version: '2.1'
services:
  app:
    build: .
    environment:
      MYAPP_DATABASE_HOST: db
      MYAPP_WEB_PORT: 8080
      DBUSER: root
      DBPASSWORD: secret
      DBNAME: myapp
      HOST: localhost
      ESERVER: Smtp.gmail.com
      EPASS: assemhapass
      EGMAIL: assemhaonline@gmail.com
      EMAIL: assemha@assemha.com
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 3000:8080
  db:
    image: healthcheck/postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: myapp
    ports:
      - 5432:5432

